services:

  db-server:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
  rest-api:
    image: noerous/proyecto_grupo1_delivery:1.0.0
    #build: .
    ports:
      - 3000:3000
    environment:
      -  PORT=3000
      -  DB_HOST=${DB_HOST}
      -  DB_PORT=${DB_PORT}
      -  DB_USER=${DB_USER}
      -  DB_PASS=${DB_PASS}
      -  DB_NAME=${DB_NAME}
    volumes:
      - code:/src
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
        
    #depends_on: #es ignorado en prod
     # - db-server
    #secrets:
    #  - config
    

  
volumes:
  code:
  postgresql-data: